### ISSUE TITLE
Here's a docker-compose for your Samsung-tvplus-for-channels 

### ISSUE THREAD

**Issue by Nostradamus1973** [matthuisman/samsung-tvplus-for-channels#13]
Hi Matt,

We've talked before, I doubt you'll remember me, but, I thanked you for all that you do for the IPTV  community.
Here's a Docker Compose that I used for your SamsungTV docker; it's not much, in fact I'm sure many of your patrons can make their own compose files and do a better job, but, for those who can't, please post this as a small thank you for all that you do.

```
version: "3.1"
services:
  samsungtv:
    container_name: samsungtv
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=America/New_York
    image: matthuisman/samsung-tvplus-for-channels
    ports:
      - 8182:80    # Web Interface Port
    volumes:
      - /home/nostradamus/dockers/samsungtv:/app/data/
    restart: unless-stopped
```

I used my home directory for placement, so, anyone can change it accordingly to fit their needs. 
Thx again Matt, Have a great day.
